### PR TITLE
Fixed compatibility with recent versions of aw-server

### PR DESCRIPTION
**Pull request by ErikBjare**
This was long overdue.

It should now work with recent versions of aw-server.

I also improved a bunch of other minor stuff.

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
Sometimes i get duplicate events, otherwise it seems to work fine

**Comment by johan-bjareholt** [comment]
Kind of unrelated, but I do get this with latest aw-core

```
2017-06-27 12:01:06,635 [WARNING]: Removed invalid field id from Event kwargs: {'id': 94, 'timestamp': '2017-06-27 09:59:18.999000+00:00', 'duration': 107.576, 'data': {'url': 'about:debugging#addons', 'title': 'Debugging with Firefox Developer Tools'}}  (aw_core.models:50)
```

**Comment by ErikBjare** [comment]
@johan-bjareholt I have a solution for the "invalid field id". Will see if I can find any reason for duplicates.

**Comment by ErikBjare** [comment]
@johan-bjareholt By the way, did you test on Chrome or Firefox?

**Comment by johan-bjareholt** [comment]
Tested only on firefox

**Comment by ErikBjare** [comment]
@johan-bjareholt Nice, I tested on Chrome so at least we've done a little testing with both,

**Pull request merged**
